#Outra opção para ordem da tabuada usando apenas 1 variável.
n1 = int(input('Digite um número: '))
print('A tabuada para o número {} é:'.format(n1))
print('=' * 12)
print('{} X {:2} = {:2}'.format(n1, 1, n1*1))
print('{} X {:2} = {}'.format(n1, 2, n1*2))
print('{} X {:2} = {}'.format(n1, 3, n1*3))
print('{} X {:2} = {}'.format(n1, 4, n1*4))
print('{} X {:2} = {}'.format(n1, 5, n1*5))
print('{} X {:2} = {}'.format(n1, 6, n1*6))
print('{} X {:2} = {}'.format(n1, 7, n1*7))
print('{} X {:2} = {}'.format(n1, 8, n1*8))
print('{} X {:2} = {}'.format(n1, 9, n1*9))
print('{} X {:2} = {}'.format(n1, 10, n1*10))
print('='*12)